name: docker-misc-${CONTAINER_NAME}_cu118
services:
  sonitranslate:
    image: ${CONTAINER_NAME}_cu118:latest
    container_name: ${CONTAINER_NAME}_cu118
    build:
      context: .
      dockerfile: Dockerfile.cu118
    working_dir: /app
    volumes:
      - .:/app
      - ${HF_HOME}:/root/.cache/huggingface
      - ${TORCH_HOME}:/root/.cache/torch
    ports:
      - 8201:7860
    command: python app_rvc.py --public_url --theme SherlockRamos/Feliz --verbosity_level debug
    # Start with bash
    # command: bash
    tty: true
    environment:
      - YOUR_HF_TOKEN=${YOUR_HF_TOKEN}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
